"""Set default attendance_date to current date

Revision ID: 6ba3adff48dc
Revises: 5ea3f371d922
Create Date: 2024-09-10 12:07:17.963911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ba3adff48dc'
down_revision: Union[str, None] = '5ea3f371d922'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
