"""Set Attendance Date to TIMESTAMP NOW()

Revision ID: 74594fa2bca3
Revises: 6ba3adff48dc
Create Date: 2024-09-13 18:57:09.265166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74594fa2bca3'
down_revision: Union[str, None] = '6ba3adff48dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attendance', 'attendance_date',
               existing_type=sa.DATE(),
               type_=sa.TIMESTAMP(timezone=True),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attendance', 'attendance_date',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
